# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test .NET projects

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    branches: [	"main" ]


jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Unit Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./src/TagzApp.UnitTest

  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest 
    defaults:
      run:
        working-directory: ./src/TagzApp.WebTest
    container:
      image: mcr.microsoft.com/playwright/dotnet:v1.35.0-jammy
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - run: dotnet build
      - name: Execute Playwright tests
        run: dotnet test --no-build
  dockerbuild:
    runs-on: ubuntu-latest
    steps:
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.1.1
      with:
        build-contexts: ./src/TagzApp.Web
        file: Dockerfile
        no-cache: false # optional, default is false
        push: true # optional, default is false
        # Generate SBOM attestation for the build (shorthand for --attest=type=sbom)
        sbom: true # optional
        # List of secrets to expose to the build (e.g., key=string, GIT_AUTH_TOKEN=mytoken)
        tags: ${ACR_HOST}/tagzapp:latest
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: ${ACR_TOKEN_USER}
        # Container registry password
        password: ${ACR_TOKEN_PASSWORD}
        # Container registry server url
        login-server: ${ACR_HOST}
